---
title: "flat_project_mgmt.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# project_mgmt

Here is what will happen when launching the app

+ Prompt for new or existing project
+ If new, create the project folder
+ If existing, list the existing projects and prompt for the project name


```{r function-project_mgmt}

#' List existing project
#'
#' List existing project saved in the shinidraw project folder
#'
#' @export
excal_existing_project <- function(){
  x <- excal_list_existing_projects()
  if (length(x) == 0) {
    cli::cli_alert_danger("No existing project")
    return(FALSE)
  }
  cat(
    paste0(
      1:length(x),
      ": ",
      x
    ),
    sep = "\n"
  )
}

excal_list_existing_projects <- function() {
  list.files(
    get_excalidraw_path()
  )
}


excal_new_or_existing <- function() {
  utils::menu(
    c("new" = "New project", "exising" = "Existing project"),
    title = "Do you wanna work on a new project or an existing one?"
  )
}

# Get a new project name
excal_prompt_new_project_name <- function() {
  # Ask the user to enter a project name
  # If the project name is valid but already exists, ask to print the existing ones
  # If yes, print the projects
  # Ask again, until project name is valid
  existing_projects <- excal_list_existing_projects()
  re_prompt <- TRUE
  while (re_prompt) {
    # Ask for a project name
    project_name <- base::readline("Enter a project name: ")
    # If the project name is already taken, ask if we want to open it
    if (project_name %in% existing_projects) {
      cli::cli_alert_danger("This project name already exists")
      open_it <- utils::askYesNo("Open it? (no to enter a new name)")
      if (!open_it) {
        next()
      }
    }
    return(project_name)
  }
}

excal_prompt_existing_project_name <- function() {
  # Ask the user to select an existing project name
  existing_projects <- excal_list_existing_projects()
  # If no existing project, create a new one by prompting the user
  if (length(existing_projects) == 0) {
    cli::cli_alert_danger("No existing project")
    project_name <- excal_prompt_new_project_name()
  } else {
    project_name <- existing_projects[utils::menu(
      existing_projects,
      title = "Select an existing project"
    )]
  }
  return(project_name)
}

handle_new_project <- function(project) {
  excal_home <- get_excalidraw_path()
  # The user hasn't prompted a project name
  if (missing(project)) {
    # Prompt for new project
    project_name <- excal_prompt_new_project_name()
  } else {
    # The user has entered a project name
    # We need to make sure this project can
    # either be created, or opened
    project_name <- project

    # If a project is specified, check if it exists
    if (dir.exists(file.path(excal_home, project_name))) {
      # It exists, we might want to open it instead of
      # creating a new one
      cli::cli_alert_danger("This project already exists.")
      open <- utils::askYesNo("Open it?")
      if (!open) {
        return(FALSE)
      }
    }
  }
  # Here, we have the name of the project, we need to build the path to it
  project_path <- file.path(excal_home, project_name)

  # Each project has its own versionning system with
  # the current date as the version
  # We create it if it does not exist
  if (!dir.exists(project_path)) {
    dir.create(project_path, recursive = TRUE)
  }
  return(
    file.path(
      project_path,
      sprintf(
        "%s.excalidraw",
        basename(project_path)
      )
    )
  )
}

handle_open_project <- function(project) {
  excal_home <- get_excalidraw_path()
  # The user hasn't prompted a project name
  if (missing(project)) {
    # Prompt for new project
    project_path <- file.path(
      excal_home,
      excal_prompt_existing_project_name()
    )
  } else {
    # The user has entered a project name
    # We need to make sure this project can
    # either be created, or opened
    project_path <- file.path(
      excal_home,
      project
    )
    # If a project is specified, check if it exists
    if (!dir.exists(project_path)) {
      # It doesn'texists, we might want to create it
      cli::cli_alert_danger("This project doesn't exists.")
      open <- utils::askYesNo("Create?")
      if (!open) {
        return(FALSE)
      }
      # project doesn't exist, we create it
      dir.create(
        project_path,
        recursive = TRUE
      )
    }
  }
  return(
    file.path(
      project_path,
      sprintf(
        "%s.excalidraw",
        basename(project_path)
      )
    )
  )
}

#' Get the path to the Excalidraw file
#'
#' Get the link to the excalidraw file
#'
#' @param project_name The name of the project
#'
#' @export
excalidraw_get_project <- function(project_name){
  excal_home <- get_excalidraw_path()
  proj <- file.path(excal_home, sprintf("%s.excalidraw", project_name))
  if (length(proj) == 0) {
    cli::cli_alert_danger("No existing project")
    return(FALSE)
  }
  return(proj)
}

```

```{r examples-project_mgmt}
if (interactive()) {
  excal_new_or_existing()
}
```

```{r tests-project_mgmt}
test_that("project_mgmt works", {
    excalidraw_consent(TRUE)
  expect_error(
    testthat::capture_output(excal_existing_project()),
    regexp = NA
  )
  expect_error(
    excal_list_existing_projects(),
    regexp = NA
  )
  expect_equal(
    length(excal_list_existing_projects()),
    length(
      list.files(
        get_excalidraw_path()
      )
    )
  )

    excalidraw_unconsent()

})
```

