---
title: "flat_consent.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# consent

```{r function-consent}
#' Consent to using shinidraw
#'
#' @return TRUE if consent is given, FALSE otherwise
#' @param force Force consent
#' @export
#' @rdname consent
#'
excalidraw_consent <- function(force = FALSE) {
  if (file.exists(
    app_sys("consent")
  )) {
    return(TRUE)
  } else {
    if (force) {
      consent <- TRUE
    } else {
      consent <- utils::askYesNo(
        "Are you ok with {shinidraw} storing data on your computer?"
      )
    }
    if (consent) {
      file.create(
        file.path(app_sys(), "consent")
      )
      return(TRUE)
    } else {
      stop("You need to accept the consent to use {shinidraw} projects.")
    }
  }
}
#' @export
#' @rdname consent
excalidraw_unconsent <- function() {
  unlink(
    app_sys("consent")
  )
}
```

```{r examples-consent}
if (interactive()) {
  excalidraw_consent()
  excalidraw_unconsent()
}
```

```{r tests-consent}
test_that("consent works", {
  excalidraw_unconsent()
  excalidraw_consent(TRUE)
  expect_true(
    file.exists(
      app_sys("consent")
    )
  )
  excalidraw_unconsent()
  expect_false(
    file.exists(
      app_sys("consent")
    )
  )
})
```


