# WARNING - Generated by {fusen} from dev/flat_project_mgmt.Rmd: do not edit by hand

test_that("project_mgmt works", {
    excalidraw_consent(TRUE)
  expect_error(
    testthat::capture_output(excalidraw_existing_project()),
    regexp = NA
  )
  expect_error(
    excalidraw_list_existing_projects(),
    regexp = NA
  )
  expect_equal(
    length(excalidraw_list_existing_projects()),
    length(
      list.files(
        get_excalidraw_path()
      )
    )
  )

    excalidraw_unconsent()

})
