# WARNING - Generated by {fusen} from dev/flat_consent.Rmd: do not edit by hand

test_that("consent works", {
	unconsent()
	consent(TRUE)
	expect_true(
		file.exists(
			app_sys("consent")
		)
	)
	unconsent()
	expect_false(
		file.exists(
			app_sys("consent")
		)
	)
})
