# WARNING - Generated by {fusen} from /dev/flat_project_mgmt.Rmd: do not edit by hand

test_that("project_mgmt works", {
  expect_error(
    testthat::capture_output(excal_existing_project()),
    regexp = NA
  )
  expect_error(
    excal_list_existing_projects(),
    regexp = NA
  )
  expect_equal(
    length(excal_list_existing_projects()),
    length(
      list.files(
        system.file("projects", package = "shinidraw")
      )
    )
  )
})
