# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("get_excalidraw_path works", {
  excalidraw_consent(TRUE)
  res <- get_excalidraw_path()
  expect_equal(res, "~/shinidraw/")
  excalidraw_unconsent()
})
