# WARNING - Generated by {fusen} from dev/flat_htmldep.Rmd: do not edit by hand

test_that("htmldep works", {
  deps <- excalidraw_dependency()
  expect_true(
    inherits(deps, "html_dependency")
  )
  expect_true(
    deps$name == "Excalidraw"
  )
  expect_true(
    deps$name == "Excalidraw"
  )
  expect_true(
    all(list.files("inst/excalidraw_deps") %in% deps$script)
  )
})

