# WARNING - Generated by {fusen} from dev/flat_consent.Rmd: do not edit by hand

test_that("consent works", {
  excalidraw_unconsent()
  excalidraw_consent(TRUE)
  expect_true(
    file.exists(
      app_sys("consent")
    )
  )
  excalidraw_unconsent()
  expect_false(
    file.exists(
      app_sys("consent")
    )
  )
})
