# WARNING - Generated by {fusen} from dev/flat_consent.Rmd: do not edit by hand

#' Consent to using shinidraw
#'
#' @return TRUE if consent is given, FALSE otherwise
#' @param force Force consent
#' @export
#' @rdname excalidraw_consent
#'
#' @examples
#' if (interactive()) {
#' 	excalidraw_consent()
#' 	excalidraw_unconsent()
#' }
excalidraw_consent <- function(force = FALSE) {
	if (file.exists(
		app_sys("consent")
	)) {
		return(TRUE)
	} else {
		if (force) {
			consent <- TRUE
		} else {
			consent <- utils::askYesNo(
				"Are you ok with {shinidraw} storing data on your computer?"
			)
		}
		if (consent) {
			file.create(
				file.path(app_sys(), "consent")
			)
			return(TRUE)
		} else {
			cli::cli_alert_warning(
				"You need to accept the consent to use {shinidraw} projects."
			)
			return(FALSE)
		}
	}
}
#' @export
#' @rdname excalidraw_consent
excalidraw_unconsent <- function() {
	unlink(
		app_sys("consent")
	)
}
