# WARNING - Generated by {fusen} from dev/flat_htmldep.Rmd: do not edit by hand

#' htmldep Title
#'
#' @return 1
#' @noRd
#' @examples
#' excal_dependency()
excal_dependency <- function() {
	htmltools::htmlDependency(
		"Excalidraw",
		"0.14.2",
		src = system.file("excalidraw_deps", package = "shinidraw"),
		script = c(
			"react.development.min.js",
			"react-dom.development.min.js",
			"excalidraw.production.min.js"
		),
		meta = list(
			charset = "UTF-8"
		),
		head = HTML(
			'<meta name="viewport" content="width=device-width, initial-scale=1">'
		)
	)
}
